### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by pchsRoboticPgram** [robotpy/robotpy-docs#18]
ERROR: Command '['C:\\Users\\PCHS Summer School\\PycharmProjects\\learning\\venv\\lib\\site-packages\\robotpy_installer\\win32\\psftp.exe', '-pw', '', '-b', 'C:\\Users\\PCHSSU~1\\AppData\\Local\\Temp\\tmpz4wmtxc8', 'lvuser@10.37.21.2']' returned non-zero exit status 2.

I was getting this error. I don't know whats wrong. help me. pls.

**Comment by virtuald** [comment]
Need more context. Presumably there is text above that message? It will most likely be instructive.

**Comment by auscompgeek** [comment]
> `mkdir /home/lvuser/py_new: failure`

Hm. Does that directory already exist? If so, looks like you're hitting robotpy/pyfrc#127. Maybe I should actually get around to fixing that…

**Comment by virtuald** [comment]
@pchsRoboticPgram please upgrade pyfrc to 2018.4.3 and try again, it should work now. Please let us know if that doesn't address your issue.

**Comment by pchsRoboticPgram** [comment]
Thank you!!!
