### ISSUE TITLE
cscore installation step not working

### ISSUE THREAD

**Issue by ColeScheller** [robotpy/robotpy-docs#32]
So I've been trying to get cscore installed on my team's raspberry pi 4 to no avail. I install using the

`robotpy-installer download-opkg cscore`

And it executes perfectly fine, no errors. Then I run the installation step,

`robotpy-installer install-opkg cscore`

Which executes fine as well. So at this point I open a terminal and open python3 and type

`import cscore` and when that didn't work I just tried `import _cscore` which didn't work either.

I'm not sure what to do from here because the installation seems to be going fine, but then I can't open it.

**Comment by virtuald** [comment]
Those instructions are in the section "RoboRIO installation". They won't work on a Raspberry Pi. See the section underneath for other types of installation.
